# bugzilla base data
BZ_URL: https://bugs.freebsd.org/bugzilla/
BZ_USER: test@example.com
BZ_PASSWD: test

PRODUCT: Ports & Packages
COMPONENT: Individual Port(s)
STATUS: ['New', 'Open', 'In Progress', 'UNCONFIRMED']

